<?php include("partial/header.php") ?>
        <div class="roster_head">
            <ul>
                <li><a href="roster.php">ROSTER DUTY</a></li>
        <li><a href="#"><span id="mark">OFFICE TRIP</span></a></li>
            </ul>
        </div>
        <div class="mytable">
            <table>
                <tbody>
                    <tr>
                        <td>Driver</td>
                        <td>Time</td>
                        <td>Sunday</td>
                        <td>Monday</td>
                        <td>Tuesday</td>
                        <td>Wednesday</td>
                        <td>Thursday</td>
                    </tr>
                    <tr>
                        <td rowspan="3">Mujib</td>
                        <td>8.50</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>1.30</td>
                        <td>Teacher</td>
                        <td></td>
                        <td></td>
                        <td>Teacher</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>2.30</td>
                        <td></td>
                        <td>Teacher</td>
                        <td>Teacher</td>
                        <td></td>
                        <td></td>
                    </tr>
                    
                    <tr>
                        <td rowspan="3">Khorsed</td>
                        <td>8.50</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>1.30</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>Teacher</td>
                    </tr>
                    <tr>
                        <td>2.30</td>
                        <td>Teacher</td>
                        <td></td>
                        <td>Staff</td>
                        <td></td>
                        <td>Teacher</td>
                    </tr>
                    
                    <tr>
                        <td rowspan="3">Barkot</td>
                        <td>8.50</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>Teacher</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>1.30</td>
                        <td></td>
                        <td>Teacher</td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>2.30</td>
                        <td>Staff</td>
                        <td></td>
                        <td></td>
                        <td>Staff</td>
                        <td></td>
                    </tr>
                    
                    <tr>
                        <td rowspan="3">Provat</td>
                        <td>8.50</td>
                        <td></td>
                        <td>Teacher</td>
                        <td>Teacher</td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>1.30</td>
                        <td></td>
                        <td>Teacher</td>
                        <td>Teacher</td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>2.30</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    
                    <tr>
                        <td rowspan="3">Anando</td>
                        <td>8.50</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>Staff</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>1.30</td>
                        <td>Staff</td>
                        <td></td>
                        <td>Staff</td>
                        <td>Teacher</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>2.30</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    
                    <tr>
                        <td rowspan="3">Ronjon</td>
                        <td>8.50</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>Staff</td>
                    </tr>
                    <tr>
                        <td>1.30</td>
                        <td>Teacher</td>
                        <td>Staff</td>
                        <td></td>
                        <td></td>
                        <td>Staff</td>
                    </tr>
                    <tr>
                        <td>2.30</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    
                    <tr>
                        <td rowspan="3">Hossen</td>
                        <td>8.50</td>
                        <td>Teacher</td>
                        <td></td>
                        <td>Staff</td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>1.30</td>
                        <td></td>
                        <td></td>
                        <td>Staff</td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>2.30</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>Teacher</td>
                        <td></td>
                    </tr>
                    
                    <tr>
                        <td rowspan="3">Ibrahim</td>
                        <td>8.50</td>
                        <td>Staff</td>
                        <td>Staff</td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>1.30</td>
                        <td></td>
                        <td></td>
                        <td>Teacher</td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>2.30</td>
                        <td></td>
                        <td>Staff</td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    
                    <tr>
                        <td rowspan="3">Mithu Borua</td>
                        <td>8.50</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>Teacher</td>
                    </tr>
                    <tr>
                        <td>1.30</td>
                        <td>Staff</td>
                        <td></td>
                        <td></td>
                        <td>Staff</td>
                        <td>Teacher</td>
                    </tr>
                    <tr>
                        <td>2.30</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    
                    <tr>
                        <td rowspan="3">Ratan Dey</td>
                        <td>8.50</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>1.30</td>
                        <td></td>
                        <td>Staff</td>
                        <td></td>
                        <td>Staff</td>
                        <td>Staff</td>
                    </tr>
                    <tr>
                        <td>2.30</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>Staff</td>
                    </tr>
                </tbody>
            </table>
        </div>
<?php include("partial/footer.php");